### ISSUE TITLE
FlexSoftAnim's velocity addition makes particles point toward gameobject's origin position

### ISSUE THREAD

**Issue by skore11** [skore11/Percubed_BEAPS#1]
This behavior probably stems from us adding velocities to the individual particles during the animation state, the flex particles follow the bone weight transformations from the ref. anim. While transferring the same to local space coordinates for the gameobject, the particles are not shifted to new positions correctly.

**Comment by strank** [comment]
FlexAnimSoftSkin had several bugs regarding correctly getting the transformations between reference animation and target flex object correct. Still missing, it seems, is that we are not taking the transform of the model import into account yet. I.e. if the mesh is already moved/rotated relative to the imported vertices.

Another issue: FlexSoftActor tries to track motion of the overall object with the "reference shape" of the asset. We should use that and treat it like a root bone - not sure yet how to deal with that.

**Comment by strank** [comment]
Closed, see commit 50a1453. Opening a separate issue for Flex's tracking of the reference shape motion.
